BEGIN;

CREATE TABLE IF NOT EXISTS "pickup_site" (
  "id" SERIAL PRIMARY KEY,
  "nom" VARCHAR(255) NOT NULL UNIQUE,
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMIT;
